SEZU_HOST_INTERFACE=ens3
SEZU_HOST_IPV4=51.81.86.225
SEZU_HOST_IPV4_GATEWAY=51.81.80.1
SEZU_HOST_IPV6=2604:2dc0:121:3e2::1/128
SEZU_HOST_IPV6_ADDRESS=2604:2dc0:121:3e2::1
SEZU_HOST_IPV6_GATEWAY=2604:2dc0:121::1
SEZU_INCUS_PROJECT=sezu
SEZU_INCUS_POOL=sezu-btrfs
SEZU_INCUS_POOL_SOURCE=/var/lib/sezu/storage/sezu-btrfs.img
SEZU_INCUS_LOOP_SOURCE=/var/lib/incus/disks/sezu-btrfs.img
SEZU_INCUS_NETWORK=sezu-br0
SEZU_INCUS_IPV4=10.177.0.1/24
SEZU_INCUS_IPV4_SUBNET=10.177.0.0/24
SEZU_INCUS_IPV6=fd42:7365:7a75::1/64
SEZU_INCUS_IPV6_SUBNET=fd42:7365:7a75::/64
SEZU_INCUS_PROFILE=sezu-u-power
SEZU_WORK_VOLUME=u-work
SEZU_CACHE_VOLUME=u-cache
SEZU_FUTURE_BUILD_INSTANCE=u-build
SEZU_FUTURE_PRODUCTION_INSTANCE=u
SEZU_FUTURE_GOLDEN_ALIAS=sezu-u-golden-0.1.0
